# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/general-conference-extractor',
                'doc_host': 'https://c-a-s-t-l-e.github.io',
                'git_url': 'https://github.com/c-a-s-t-l-e/general-conference-extractor',
                'lib_path': 'general_conference_extractor'},
  'syms': { 'general_conference_extractor.GeneralConferenceTalk': { 'general_conference_extractor.GeneralConferenceTalk.GeneralConferenceTalk': ( 'generalconferencetalk.html#generalconferencetalk',
                                                                                                                                                  'general_conference_extractor/GeneralConferenceTalk.py'),
                                                                    'general_conference_extractor.GeneralConferenceTalk.GeneralConferenceTalk.__init__': ( 'generalconferencetalk.html#generalconferencetalk.__init__',
                                                                                                                                                           'general_conference_extractor/GeneralConferenceTalk.py'),
                                                                    'general_conference_extractor.GeneralConferenceTalk.GeneralConferenceTalk._extract_metadata': ( 'generalconferencetalk.html#generalconferencetalk._extract_metadata',
                                                                                                                                                                    'general_conference_extractor/GeneralConferenceTalk.py'),
                                                                    'general_conference_extractor.GeneralConferenceTalk.GeneralConferenceTalk._extract_text': ( 'generalconferencetalk.html#generalconferencetalk._extract_text',
                                                                                                                                                                'general_conference_extractor/GeneralConferenceTalk.py')},
            'general_conference_extractor.core': { 'general_conference_extractor.core.foo': ( 'core.html#foo',
                                                                                              'general_conference_extractor/core.py')},
            'general_conference_extractor.extractURLs': { 'general_conference_extractor.extractURLs.extract_talk_urls': ( 'extract_urls.html#extract_talk_urls',
                                                                                                                          'general_conference_extractor/extractURLs.py')}}}
