# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/general-conference-extractor',
                'doc_host': 'https://c-a-s-t-l-e.github.io',
                'git_url': 'https://github.com/c-a-s-t-l-e/general-conference-extractor',
                'lib_path': 'general_conference_extractor'},
  'syms': { 'general_conference_extractor.core': { 'general_conference_extractor.core.foo': ( 'core.html#foo',
                                                                                              'general_conference_extractor/core.py')}}}
